"""Change telemetry

Revision ID: 74153c1ecc31
Revises: 8883598427a4
Create Date: 2026-04-23 09:43:11.092923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74153c1ecc31'
down_revision: Union[str, Sequence[str], None] = '8883598427a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('applications', 'config',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('telemetry', sa.Column('target', sa.String(length=50), nullable=False))
    op.add_column('telemetry', sa.Column('type', sa.String(length=30), nullable=False))
    op.add_column('telemetry', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('telemetry_cluster_id_fkey'), 'telemetry', type_='foreignkey')
    op.drop_column('telemetry', 'name')
    op.drop_column('telemetry', 'cluster_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('telemetry_cluster_id_fkey'), 'telemetry', 'clusters', ['cluster_id'], ['id'])
    op.drop_column('telemetry', 'created_at')
    op.drop_column('telemetry', 'type')
    op.drop_column('telemetry', 'target')
    op.alter_column('applications', 'config',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
