"""add ip in cluster, add port in application, add config in application

Revision ID: 8883598427a4
Revises: a0ed25aeb918
Create Date: 2026-01-21 15:00:26.740188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8883598427a4'
down_revision: Union[str, Sequence[str], None] = 'a0ed25aeb918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('config', sa.String(length=2), nullable=False))
    op.add_column('applications', sa.Column('port', sa.Integer(), nullable=False))
    op.drop_column('applications', 'status')
    op.add_column('clusters', sa.Column('ip_address', sa.String(length=15), nullable=False))
    op.drop_column('clusters', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('region', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('clusters', 'ip_address')
    op.add_column('applications', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('applications', 'port')
    op.drop_column('applications', 'config')
    # ### end Alembic commands ###
