"""change application table

Revision ID: d71770c5ba63
Revises: c03bd2cdee43
Create Date: 2026-05-05 09:51:43.499706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71770c5ba63'
down_revision: Union[str, Sequence[str], None] = 'c03bd2cdee43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('num_replicas', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'num_replicas')
    # ### end Alembic commands ###
