"""add cluster capacity and application last latency

Revision ID: e546577693dd
Revises: d71770c5ba63
Create Date: 2026-05-16 15:05:50.460869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e546577693dd'
down_revision: Union[str, Sequence[str], None] = 'd71770c5ba63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('last_latency_check', sa.Float(), nullable=False))
    op.add_column('applications', sa.Column('last_latency_counter', sa.Integer(), nullable=False))
    op.add_column('clusters', sa.Column('cores', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'cores')
    op.drop_column('applications', 'last_latency_counter')
    op.drop_column('applications', 'last_latency_check')
    # ### end Alembic commands ###
