"""add port to component

Revision ID: fdb0ba50895c
Revises: 86a1f9c5b18e
Create Date: 2026-06-08 10:07:49.327644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb0ba50895c'
down_revision: Union[str, Sequence[str], None] = '86a1f9c5b18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('port', sa.Integer(), nullable=False))
    op.drop_column('components', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('config', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('components', 'port')
    # ### end Alembic commands ###
